- name: configure redis server 
  hosts: redis 
  become: yes 
  tasks:
  - name: disable latest version and enable old version  
    ansible.builtin.command: dnf module disable redis -y
    ansible.builtin.command: dnf module enable redis:7 -y
  - name: install redis 
    ansible.builtin.package:
      name: redis 
      state: present 

  - name: start and enable the mongodb server 
    ansible.builtin.service:
      name: redis
      state: started
      enabled: true 

  - name: set remote setup 
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: 127.0.0.1
      replace: 0.0.0.0

  - name: set remote setup protection mode
    ansible.builtin.replace:
      path: /etc/redis/redis.conf
      regexp: protected-mode yes
      replace: protected-mode no 

  - name: restart the mongodb server
    ansible.builtin.service:
      name: redis
      state: restarted
